- name: How to build your own unhealthy_xxx_list
  hosts: bastion
  vars:
    envconfig: kind-app-1-cluster
  tasks:
    - name: Check node states
      shannonhung.my_collection.health_check:
        targets: "{{ groups['node'] }}"
        envconfig: "{{ envconfig }}"
        desired_missing: true   # 在 inventory 可是不在 k8s
        current_missing: true   # 在 k8s 但是不在 inventory
        node_not_ready: true    # 在 k8s 裡面狀態不是 Ready
        unhealthy_label:
          - { "cordon_reason": "PM" }
          - { "node.kubernetes.io/unreachable": "true" }
      register: result

    - name: Debug show my_collection.health_check
      debug:
        var: result.results

    # 整理一下目前的 list 後面可以做擴增
    - name: Set result as facts
      set_fact:
        current_missing_list: "{{ result.results.current_missing_list }}"
        desired_missing_list: "{{ result.results.desired_missing_list }}"
        node_not_ready_list: "{{ result.results.node_not_ready_list }}"
        unhealthy_label_list: "{{ result.results.unhealthy_label_list }}"
        unhealthy_node_list: "{{ result.results.unhealthy_node_list }}"
        failed_ping_list: []  # 或是新增自己在這個 roles 要另外檢查的項目
        # 可以自己組合 unhealthy_node_list
#        unhealthy_node_list: "{{ result.results.node_not_ready_list + result.results.unhealthy_label_list }}"

- name: Ping all hosts and add failed hosts to 'ping_failed' list
  hosts: node
  gather_facts: no
  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_errors: yes

    - name: Add failed hosts to ping_failed_list
      set_fact:
        ping_failed_list: "{{ ping_failed_list + [inventory_hostname] | unique }}"
        unhealthy_node_list: "{{ unhealthy_node_list + [inventory_hostname] | unique }}"
      when: ping_result.failed

    - name: Debug show ping_failed_list
      debug:
        var: ping_failed_list

- name: Show unhealthy_groups facts


#        - name: Show ping register ping_result
#          debug:
#            var: ping_result

#        - name: Add unreachable nodes to unhealthy_node_list and ping_failed_list
#          set_fact:
#            diff_unhealthy_groups: >-
#              {{
#                diff_unhealthy_groups | combine({
#                  'unhealthy_node_list': diff_unhealthy_groups.unhealthy_node_list + (ping_result.results | selectattr('failed', 'equalto', true) | map(attribute='item') | list),
#                  'ping_failed_list': diff_unhealthy_groups.ping_failed_list + (ping_result.results | selectattr('failed', 'equalto', true) | map(attribute='item') | list)
#                })
#              }}
#          when: ping_result.results is defined

#    - name: Show diff_healthy_groups
#      debug:
#        var: diff_healthy_groups
    # 如何添加自己定義的 unhealthy group
    # 例如 ping failed
#    - name: Add ping failed into ping_failed_list

      # 建立 inventory groups
#    - name: Add unhealthy_node hosts to group
#      ansible.builtin.add_host:
#        name: "{{ item }}"
#        groups: unhealthy_node
#      loop: "{{ result.results.unhealthy_node_list }}"
#
#    - name: Show new inventory groups
#      debug:
#        var: groups
