- name: Init current states groups
  hosts: localhost
  gather_facts: no
  tasks:
    # (Step1) 使用 unhealthy check action plugin
    # <<< 注意，以下各種 list 都是存在 localhost 所以如果在其他 node 使用也一定要使用
    # <<< - delegate_to: localhost 以及 delegate_facts: true 回去 localhost 更新狀態
    - name: Start Health Check
      include_role:
        name: shannonhung.my_collection.health_check
      vars:                               #<<< (1.1) envconfig 一要提供 也可以替換其他變數
        targets: "{{ groups['node'] }}"
        envconfig: kind-app-1-cluster
      run_once: true

    # (1.3) 可以用來查看結果
    - name: Before Show Health Check Result
      include_role:
        name: shannonhung.my_collection.show_results
      run_once: true

    # (Step 2) 除了透過 true, false 選擇要不要整理 list，可以重新決定對於自己的 roles 來說 unhealthy_node_list 的定義
    - name: Redefined unhealthy_node_list
      set_fact:
        unhealthy_node_list: "{{ current_missing_list + desired_missing_list + node_not_ready_list + unhealthy_label_list | unique }}"
      run_once: true

    - name: After Show result
      include_role:
        name: shannonhung.my_collection.show_results
      run_once: true